#默认配置文件 ${server.groupCode} 含义为当前服务配置的groupCode，会在注册时默认设置为当前服务server.groupCode,开发态可修改，非开发态不可修改，如果为云管则写死为ROOT
operaRoute:
  boo:
  - ${server.groupCode}/FOO_SERVER_DEMO2_1.0.0
  - ${server.groupCode}/FOO_SERVER_DEMO3_1.0.0



